server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

#  profile:
#    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

